import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import RootLayout from '@/components/Layouts/RootLayout';
import Banner from '@/components/UI/Banner';


const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Banner />
      </main>
    </>
  );
};

export default HomePage;

HomePage.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};